name: 'Create channel'
description: 'Create a slack channel'
inputs:
  channel-to-create:
    description: 'The name of the channel to create'
    required: true
  bot-oauth-secret:
    description: 'The OAuth secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.ts'
