name: 'Create channel'
description: 'Create a slack channel'
inputs:
  action-type:
    description: 'The name of the channel to create'
    required: true
  bot-oauth-secret:
    description: 'The slack API OAuth secret'
    required: true
  github-token:
    description: 'The GITHUB_SECRET OAuth secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
